### ISSUE TITLE
High false positive rate

### ISSUE THREAD

**Issue by fpiedrah** [bogdan-kulynych/mia#3]
Hi! I've been playing a bit with the library, great job I really liked it! but while running the CIFAR-10 on my machine I've found that I get a fairly high False Positive Rate, any suggestions on how to reduce them? am I doing something wrong here? Thanks for the help! 

[The example code I'm running ](https://github.com/fpiedrah/Membership-Inference/blob/master/Code/cifar_10_data_set.ipynb) -- The confusion matrix at the end of the notebook

**Comment by hyoonsoo** [comment]
hey
did you find any solution of this issue???
I got similar problem.
My attack model accuracy is 50 percent.
